import React, { useState, useEffect } from 'react';
import { Checkbox } from '@/components/ui/checkbox';
import { Field, Input, Select } from '@/components/ui-kit';

interface CronBuilderProps {
    value: string;
    onChange: (value: string) => void;
}

export function CronBuilder({ value, onChange }: CronBuilderProps) {
    const [period, setPeriod] = useState<string>('daily');
    const [time, setTime] = useState<string>('09:00');
    const [daysOfWeek, setDaysOfWeek] = useState<string[]>([]);
    const [dayOfMonth, setDayOfMonth] = useState<string>('1');

    // Parse initial cron value
    useEffect(() => {
        if (!value) return;
        // Simple parser for standard formats generated by this builder
        const parts = value.split(' ');
        if (parts.length !== 5) return;

        const [minute, hour, dom, _month, dow] = parts;

        if (dom === '*' && dow === '*') {
            setPeriod('daily');
        } else if (dom === '*' && dow !== '*') {
            setPeriod('weekly');
            setDaysOfWeek(dow.split(','));
        } else if (dom !== '*' && dow === '*') {
            setPeriod('monthly');
            setDayOfMonth(dom);
        } else if (dom === '*' && dow === '*' && hour === '*') {
            setPeriod('hourly');
        }

        if (hour !== '*' && minute !== '*') {
            const h = hour.padStart(2, '0');
            const m = minute.padStart(2, '0');
            setTime(`${h}:${m}`);
        }
    }, [value]);

    const updateCron = (newPeriod: string, newTime: string, newDays: string[], newDom: string) => {
        const [h, m] = newTime.split(':').map(Number);

        let cron = '';
        switch (newPeriod) {
            case 'hourly':
                cron = `${m} * * * *`;
                break;
            case 'daily':
                cron = `${m} ${h} * * *`;
                break;
            case 'weekly':
                const days = newDays.length > 0 ? newDays.join(',') : '*';
                cron = `${m} ${h} * * ${days}`;
                break;
            case 'monthly':
                cron = `${m} ${h} ${newDom} * *`;
                break;
            default:
                cron = '* * * * *';
        }
        onChange(cron);
    };

    const handlePeriodChange = (val: string) => {
        setPeriod(val);
        updateCron(val, time, daysOfWeek, dayOfMonth);
    };

    const handleTimeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const val = e.target.value;
        setTime(val);
        updateCron(period, val, daysOfWeek, dayOfMonth);
    };

    const handleDayToggle = (day: string) => {
        const newDays = daysOfWeek.includes(day)
            ? daysOfWeek.filter(d => d !== day)
            : [...daysOfWeek, day];
        setDaysOfWeek(newDays);
        updateCron(period, time, newDays, dayOfMonth);
    };

    return (
        <div className="space-y-4 p-4 border border-border rounded-lg">
            <Field label="Frequency">
                <Select
                    value={period}
                    onChange={handlePeriodChange}
                    options={[
                        { value: 'hourly', label: 'Hourly' },
                        { value: 'daily', label: 'Daily' },
                        { value: 'weekly', label: 'Weekly' },
                        { value: 'monthly', label: 'Monthly' },
                    ]}
                />
            </Field>

            {period !== 'hourly' && (
                <Field label="Time">
                    <Input
                        type="time"
                        value={time}
                        onChange={handleTimeChange}
                    />
                </Field>
            )}

            {period === 'weekly' && (
                <div className="space-y-2">
                    <label className="text-sm font-medium text-foreground">Days</label>
                    <div className="flex flex-wrap gap-2">
                        {[
                            { val: '1', label: 'Mon' },
                            { val: '2', label: 'Tue' },
                            { val: '3', label: 'Wed' },
                            { val: '4', label: 'Thu' },
                            { val: '5', label: 'Fri' },
                            { val: '6', label: 'Sat' },
                            { val: '0', label: 'Sun' },
                        ].map((day) => (
                            <div key={day.val} className="flex items-center gap-x-2">
                                <Checkbox
                                    id={`day-${day.val}`}
                                    checked={daysOfWeek.includes(day.val)}
                                    onCheckedChange={() => handleDayToggle(day.val)}
                                />
                                <label htmlFor={`day-${day.val}`} className="text-sm cursor-pointer">
                                    {day.label}
                                </label>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {period === 'monthly' && (
                <Field label="Day of Month">
                    <Select
                        value={dayOfMonth}
                        onChange={(val) => {
                            setDayOfMonth(val);
                            updateCron(period, time, daysOfWeek, val);
                        }}
                        options={Array.from({ length: 31 }, (_, i) => ({
                            value: (i + 1).toString(),
                            label: (i + 1).toString(),
                        }))}
                    />
                </Field>
            )}

            <div className="text-xs text-muted-foreground mt-2">
                Cron Expression: <code className="bg-muted px-1 py-0.5 rounded">{value}</code>
            </div>
        </div>
    );
}
