'use client';

import { ModuleShell } from '@/components/shell/module-shell';
import { AuditLogViewer } from '@/components/crm/shared/audit-log-viewer';
import { CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ShieldCheck } from 'lucide-react';

export default function ComplianceWarningsPage() {
  return (
    <ModuleShell
      title="Compliance"
      icon={ShieldCheck}
      meta="Review compliance warnings generated by WhatsApp messaging"
      contentClassName="flex flex-col gap-3 pb-8"
    >
      <div className="rounded-xl border border-border bg-card">
        <CardHeader>
          <CardTitle>Warnings Feed</CardTitle>
          <CardDescription>
            These events are logged in audit logs. Use filters to narrow by action or date.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <AuditLogViewer changeField="whatsapp_compliance_warning" />
        </CardContent>
      </div>
    </ModuleShell>
  );
}
