/**
 * Goal Mode — Strategy Tools (Phase 1, 2026-06-05)
 *
 * Connects the chat agent to the strategy pipeline (src/lib/strategy/) so a
 * stated business goal becomes executing missions with ONE human approval:
 *
 *   user states goal
 *     → generate_strategy   (draft — never gated)
 *     → agent presents the strategy in chat
 *     → activate_strategy   (hitlPolicy 'always' → approval card = THE approval)
 *         → decomposeStrategy → instantiateRoadmap → missions spawn
 *     → iterate_strategy    (new draft version from performance data)
 *
 * The strategy artifact is also mirrored into the Agent Workspace
 * (Strategies/) so the owner can read and annotate it.
 */

import { z } from 'zod';
import { tool } from 'ai';
import { AgentContext } from './types';
import { toolRegistry } from '../tool-registry';
import { generateStrategy, decomposeStrategy } from '@/lib/strategy/generator';
import { instantiateRoadmap, iterateStrategy } from '@/lib/strategy/instantiate';
import { strategyRepository } from '@/lib/db/repository/strategy.repository';
import { writeWorkspaceDoc } from '@/lib/agent/workspace';
import type { IStrategy } from '@/lib/db/models/strategy.model';

function summarizeStrategy(strategy: IStrategy) {
    return {
        strategyId: (strategy._id as { toString(): string }).toString(),
        name: strategy.name,
        description: strategy.description,
        version: strategy.version,
        status: strategy.status,
        goals: strategy.goals?.map((g) => ({ kpi: g.kpi, target: g.target, deadline: g.deadline })),
        channels: strategy.channels,
        contentMix: strategy.contentMix,
        cadence: strategy.cadence,
        qualityScore: strategy.validation?.qualityScore,
        validationStatus: strategy.validation?.status,
    };
}

/**
 * Honest one/two-sentence confidence line derived from the validation subdoc.
 * Returns '' for legacy strategies with no validation (back-compat — no line).
 */
function buildConfidenceLine(strategy: IStrategy): string {
    const v = strategy.validation;
    if (!v) return '';

    let line = `Draft strategy ready (quality ${v.qualityScore}/100).`;

    const errors = (v.deterministic ?? []).filter((i) => i.severity === 'error');
    const warns = (v.deterministic ?? []).filter((i) => i.severity === 'warn');
    if (errors.length) {
        line += ' ' + errors.slice(0, 2).map((i) => `flagged: ${i.message}`).join(' ');
    } else if (warns.length) {
        line += ' ' + warns.slice(0, 2).map((i) => `note: ${i.message}`).join(' ');
    }

    if (v.critic?.summary) {
        line += ` ${v.critic.summary}`;
    }

    if (v.status === 'failed') {
        line = `⚠️ This draft has unresolved issues — review carefully before activating. ${line}`;
    }

    return line;
}

function strategyToHtml(strategy: IStrategy): string {
    const goals = (strategy.goals ?? [])
        .map((g) => `<li><strong>${g.kpi}</strong>: ${g.target}${g.deadline ? ` (by ${new Date(g.deadline).toISOString().slice(0, 10)})` : ''}</li>`)
        .join('');
    const channels = (strategy.channels ?? []).join(', ');
    const cadence = Object.entries(strategy.cadence ?? {})
        .map(([k, v]) => `${k}: ${v}`)
        .join(' · ');
    return `<h1>${strategy.name} (v${strategy.version})</h1>
<p>${strategy.description ?? ''}</p>
<h2>Goals</h2><ul>${goals}</ul>
<h2>Channels</h2><p>${channels}</p>
<h2>Cadence</h2><p>${cadence}</p>
<p><em>Generated by the agent. Status: ${strategy.status}.</em></p>`;
}

// ─── generate_strategy ────────────────────────────────────────────────────────

const generateStrategyParams = z.object({
    goal: z.string().min(10).max(500).describe('The business goal in the user\'s words, e.g. "Grow from 100 to 200 orders/day in 90 days" or "Take our SaaS from 1k to 10k users".'),
    constraints: z.string().max(500).optional().describe('Budget limits, channels to avoid, brand constraints.'),
});

export const generateStrategyTool = {
    name: 'generate_strategy',
    description: 'Generate a versioned, data-driven marketing strategy (draft) for a stated business goal — goals/KPIs, channel mix, content mix, cadence. Present the result to the user, refine if asked, then call activate_strategy to turn it into executing missions (that step requires approval).',
    parameters: generateStrategyParams,
    hitlPolicy: 'never' as const,
    factory: (context: AgentContext) => tool({
        description: 'Generate a draft strategy for a business goal.',
        parameters: generateStrategyParams,
        execute: async (args) => {
            try {
                if (!context.brandId) {
                    return { success: false, error: 'A brand context is required to generate a strategy.' };
                }
                const strategy = await generateStrategy({
                    orgId: context.userId,
                    brandId: context.brandId,
                    goal: args.goal,
                    constraints: args.constraints,
                    userId: context.userId,
                });

                // Mirror into the workspace so the owner can read/annotate it.
                void writeWorkspaceDoc({
                    userId: context.userId,
                    brandId: context.brandId,
                    folder: 'Strategies',
                    title: `${strategy.name} (v${strategy.version})`,
                    content: strategyToHtml(strategy),
                }).catch((error) => console.error('[generate_strategy] workspace mirror failed:', error));

                const confidence = buildConfidenceLine(strategy);
                return {
                    success: true,
                    ...summarizeStrategy(strategy),
                    qualityScore: strategy.validation?.qualityScore,
                    validationStatus: strategy.validation?.status,
                    confidence,
                    message: `${confidence ? `${confidence} ` : ''}Present it to the user; call activate_strategy when they want it executed (that will request approval).`,
                    deepLink: `/agent/strategies/${(strategy._id as { toString(): string }).toString()}`,
                };
            } catch (error) {
                return { success: false, error: error instanceof Error ? error.message : String(error) };
            }
        },
    }),
};

// ─── get_strategy ─────────────────────────────────────────────────────────────

const getStrategyParams = z.object({
    strategyId: z.string().describe('Strategy ID from generate_strategy or the strategies list.'),
});

export const getStrategyTool = {
    name: 'get_strategy',
    description: 'Fetch a strategy with its roadmap and mission progress.',
    parameters: getStrategyParams,
    hitlPolicy: 'never' as const,
    factory: (context: AgentContext) => tool({
        description: 'Fetch a strategy and its roadmap.',
        parameters: getStrategyParams,
        execute: async (args) => {
            try {
                const strategy = await strategyRepository.findById(args.strategyId);
                if (!strategy) {
                    return { success: false, error: 'Strategy not found.' };
                }
                const roadmap = await strategyRepository.getRoadmap(args.strategyId);
                return {
                    success: true,
                    ...summarizeStrategy(strategy as IStrategy),
                    roadmap: roadmap
                        ? (roadmap.entries as Array<{ id: string; title: string; status: string; dependsOn: string[]; missionId?: string }>).map((e) => ({
                            id: e.id,
                            title: e.title,
                            status: e.status,
                            dependsOn: e.dependsOn,
                            missionId: e.missionId,
                        }))
                        : null,
                };
            } catch (error) {
                return { success: false, error: error instanceof Error ? error.message : String(error) };
            }
        },
    }),
};

// ─── activate_strategy ────────────────────────────────────────────────────────

const activateStrategyParams = z.object({
    strategyId: z.string().describe('The draft strategy to activate.'),
});

export const activateStrategyTool = {
    name: 'activate_strategy',
    description: 'THE one-approval step of Goal Mode: decompose the strategy into a dependency-ordered roadmap, spawn a mission for every unblocked entry, and mark the strategy active. Requires user approval — the approval card is the user\'s sign-off on executing the whole strategy.',
    parameters: activateStrategyParams,
    hitlPolicy: 'always' as const,
    factory: (context: AgentContext) => tool({
        description: 'Decompose a strategy and spawn its missions (gated).',
        parameters: activateStrategyParams,
        execute: async (args) => {
            try {
                if (!context.brandId) {
                    return { success: false, error: 'A brand context is required to activate a strategy.' };
                }
                const strategy = await strategyRepository.findById(args.strategyId);
                if (!strategy) {
                    return { success: false, error: 'Strategy not found.' };
                }

                // 1. Decompose (idempotent — reuses/updates the roadmap).
                const decomposed = await decomposeStrategy(args.strategyId, {
                    orgId: context.userId,
                    brandId: context.brandId,
                    userId: context.userId,
                });

                // 2. Spawn missions for unblocked entries.
                const result = await instantiateRoadmap({
                    strategyId: args.strategyId,
                    orgId: context.userId,
                    brandId: context.brandId,
                    userId: context.userId,
                });

                // 3. Mark active.
                await strategyRepository.updateStatus(args.strategyId, 'active');

                const roadmapSize = (decomposed.roadmap as unknown[])?.length ?? 0;

                return {
                    success: true,
                    strategyId: args.strategyId,
                    roadmapEntries: roadmapSize,
                    missionsCreated: result.instantiated.length,
                    missionIds: result.instantiated,
                    deferredEntries: result.deferred.length,
                    message: `Strategy activated: ${roadmapSize} roadmap entries, ${result.instantiated.length} missions started now, ${result.deferred.length} waiting on dependencies. Suggest the user schedules a weekly iterate_strategy check (create_scheduled_task) to keep the strategy data-driven.`,
                    deepLink: `/agent/strategies/${args.strategyId}`,
                };
            } catch (error) {
                return { success: false, error: error instanceof Error ? error.message : String(error) };
            }
        },
    }),
};

// ─── iterate_strategy ─────────────────────────────────────────────────────────

const iterateStrategyParams = z.object({
    strategyId: z.string().describe('The strategy to iterate (will be archived; a new version is generated).'),
    performanceNotes: z.string().max(2000).optional()
        .describe('What worked and what did not. Omit to auto-gather a 30-day cross-channel report.'),
});

export const iterateStrategyTool = {
    name: 'iterate_strategy',
    description: 'Create the next version of a strategy from performance data — archives the current version and generates an improved draft (channel weights, cadence). Auto-gathers a 30-day cross-channel report when no notes are given. Activate the new version with activate_strategy (approval).',
    parameters: iterateStrategyParams,
    hitlPolicy: 'never' as const,
    factory: (context: AgentContext) => tool({
        description: 'Generate the next strategy version from performance data.',
        parameters: iterateStrategyParams,
        execute: async (args) => {
            try {
                if (!context.brandId) {
                    return { success: false, error: 'A brand context is required.' };
                }
                const strategy = await strategyRepository.findById(args.strategyId);
                if (!strategy) {
                    return { success: false, error: 'Strategy not found.' };
                }

                let performanceData = args.performanceNotes;
                if (!performanceData) {
                    try {
                        const { CrossChannelAnalyticsService } = await import('@/lib/services/cross-channel-analytics');
                        const report = await CrossChannelAnalyticsService.getReport(
                            context.brandId,
                            context.userId,
                            '30d',
                        );
                        performanceData = JSON.stringify(report).slice(0, 4000);
                    } catch (reportError) {
                        console.error('[iterate_strategy] cross-channel report failed:', reportError);
                        performanceData = 'No performance data available — keep goals, rebalance toward the lowest-effort channels.';
                    }
                }

                const newStrategy = await iterateStrategy({
                    strategyId: args.strategyId,
                    orgId: context.userId,
                    brandId: context.brandId,
                    userId: context.userId,
                    performanceData,
                    autoActivate: false, // Goal Mode: activation goes through the approval gate.
                });

                void writeWorkspaceDoc({
                    userId: context.userId,
                    brandId: context.brandId,
                    folder: 'Strategies',
                    title: `${newStrategy.name} (v${newStrategy.version})`,
                    content: strategyToHtml(newStrategy as IStrategy),
                }).catch((error) => console.error('[iterate_strategy] workspace mirror failed:', error));

                const confidence = buildConfidenceLine(newStrategy as IStrategy);
                return {
                    success: true,
                    ...summarizeStrategy(newStrategy as IStrategy),
                    qualityScore: (newStrategy as IStrategy).validation?.qualityScore,
                    validationStatus: (newStrategy as IStrategy).validation?.status,
                    confidence,
                    message: `${confidence ? `${confidence} ` : ''}New version generated from performance data. Call activate_strategy to decompose it into missions (requires approval).`,
                };
            } catch (error) {
                return { success: false, error: error instanceof Error ? error.message : String(error) };
            }
        },
    }),
};

toolRegistry.register(generateStrategyTool);
toolRegistry.register(getStrategyTool);
toolRegistry.register(activateStrategyTool);
toolRegistry.register(iterateStrategyTool);
